services:
  - type: web
    name: cryptoagentsadp-all
    env: node
    region: singapore
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node src/server.js
    branches:
      - main